# Generated by Django 6.0.5 on 2026-05-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('pg_type', models.CharField(choices=[('MALE', "Men's PG"), ('FEMALE', "Women's PG"), ('UNISEX', 'Unisex PG')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.pgowner')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(help_text='Number of beds (e.g. 2, 3, 4)')),
                ('is_ac', models.BooleanField(default=False)),
                ('base_rent', models.DecimalField(decimal_places=2, help_text='Base rent per bed', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('pg_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
        ),
    ]
