# Generated by Django 6.0.5 on 2026-05-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='electricity_cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit in ₹', max_digits=6),
        ),
    ]
