# Generated by Django 6.0.5 on 2026-05-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pending_due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
