# Generated by Django 6.0.5 on 2026-05-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_pending_due_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='pending_due_amount',
        ),
        migrations.CreateModel(
            name='TenantDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('MONTHLY_RENT', 'Monthly Rent'), ('ELECTRICITY', 'Electricity Bill'), ('SECURITY_DEPOSIT', 'Security Deposit'), ('MAINTENANCE', 'Maintenance Charges'), ('DAMAGE', 'Damage Charges'), ('LATE_PAYMENT', 'Late Payment'), ('FOOD', 'Food Charges'), ('OTHER', 'Other')], max_length=20)),
                ('custom_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
