# Generated by Django 6.0.5 on 2026-05-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_tenant_pending_due_amount_tenantdue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantdue',
            options={},
        ),
        migrations.AlterField(
            model_name='tenantdue',
            name='reason',
            field=models.CharField(choices=[('RENT', 'Monthly Rent'), ('ELECTRICITY', 'Electricity Bill'), ('DEPOSIT', 'Security Deposit'), ('MAINTENANCE', 'Maintenance Charges'), ('DAMAGE', 'Damage Charges'), ('LATE_FEE', 'Late Payment'), ('FOOD', 'Food Charges'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantdue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('CLEARED', 'Cleared')], default='PENDING', max_length=15),
        ),
    ]
