# Generated by Django 6.0.5 on 2026-05-27 10:32

import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenantdue_options_alter_tenantdue_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdocument',
            name='file',
            field=models.FileField(upload_to=utils.file_uploads.get_tenant_document_upload_path),
        ),
    ]
