# Generated by Django 6.0.5 on 2026-05-27 14:35

import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenantdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_uploads.get_tenant_photo_upload_path),
        ),
    ]
