# Generated by Django 6.0.5 on 2026-05-28 07:25

import utils.file_uploads
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_uploads.get_tenant_photo_upload_path, validators=[utils.validators.validate_file_size, utils.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='file',
            field=models.FileField(upload_to=utils.file_uploads.get_tenant_document_upload_path, validators=[utils.validators.validate_file_size, utils.validators.validate_document_extension]),
        ),
    ]
