# Generated by Django 6.0.5 on 2026-05-27 08:02

import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_tenant_payment_tenant_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='screenshot',
            field=models.ImageField(upload_to=utils.file_uploads.get_payment_screenshot_upload_path),
        ),
    ]
