# Generated by Django 6.0.5 on 2026-05-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentproof_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
