# Generated by Django 6.0.5 on 2026-05-27 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentproof_rejected_at'),
        ('properties', '0002_property_electricity_cost_per_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_electricity_bills', to=settings.AUTH_USER_MODEL)),
                ('pg_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_bills', to='properties.property')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_bills', to='properties.room')),
            ],
        ),
        migrations.DeleteModel(
            name='ElectricityBill',
        ),
    ]
