# Generated by Django 6.0.5 on 2026-05-27 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_roomelectricitybill_delete_electricitybill'),
        ('properties', '0002_property_electricity_cost_per_unit'),
        ('tenants', '0006_tenant_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_type', models.CharField(choices=[('RENT', 'Monthly Rent'), ('ELECTRICITY', 'Electricity Bill'), ('DEPOSIT', 'Security Deposit'), ('OTHER', 'Other')], default='RENT', max_length=20)),
                ('invoice_month', models.DateField()),
                ('invoice_year', models.IntegerField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PAID', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_invoice', to='payments.payment')),
                ('pg_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_invoices', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_invoices', to='tenants.tenant')),
            ],
        ),
    ]
