# Generated by Django 6.0.5 on 2026-05-28 07:25

import utils.file_uploads
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_generatedinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedinvoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.file_uploads.get_invoice_upload_path, validators=[utils.validators.validate_file_size, utils.validators.validate_pdf_extension]),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='screenshot',
            field=models.ImageField(upload_to=utils.file_uploads.get_payment_screenshot_upload_path, validators=[utils.validators.validate_file_size, utils.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='propertypaymentsettings',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_uploads.get_property_qrcode_upload_path, validators=[utils.validators.validate_file_size, utils.validators.validate_image_extension]),
        ),
    ]
